[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

# mold 快速链接器
[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-Zshare-generics=y",
]
